{% set name = "whenever" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ariebovenberg/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0355be01b73dd369eca2a3bdc1e51305bf1511d6ddc34ccd7b2e15d20639f5a7

build:
  skip: true  # [py<39]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools-rust >=1.9
    - pip
    - setuptools
    - wheel
  run:
    - python
    - tzdata >=2020.1  # [win]

test:
  imports:
    - whenever
  commands:
    # only do pip check with linux and osx because somehow it fails to detect tzdata even though it's clearly installed on win builds
    - pip check  # [not win]
  requires:
    - pip

about:
  home: https://github.com/ariebovenberg/whenever
  doc_url: https://whenever.readthedocs.io/en/latest/
  summary: Foolproof datetimes for maintainable code
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
