{% set name = "whenever" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whenever-{{ version }}.tar.gz
  sha256: b9d442844c557a90df9acd5a99e2413caa5187c769057d31feaa1909b0927b35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.1.0
    - pip
  run:
    - python >=3.9,<4.0

test:
  imports:
    - whenever
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ariebovenberg/whenever
  doc_url: https://whenever.readthedocs.io/en/latest/
  summary: Foolproof datetimes for maintainable code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
